import {
  CircleDollarSign,
  Car,
  House,
  Utensils,
  ShoppingBag,
  Briefcase,
  ArrowLeftRight,
  ChartNoAxesCombined,
  Shapes,
  BookOpen,
  Bus,
  HeartPulse,
  PawPrint,
  Plane,
  ReceiptText,
  Film,
  Gift,
  PiggyBank,
  Landmark,
  Dumbbell,
  Smartphone,
  Coffee,
  Receipt,
  Store,
  Percent,
  TrendingUp,
  RotateCcw,
  CirclePlus,
  GraduationCap,
  Lightbulb,
  Shield,
  Building,
  Sparkles,
  CircleMinus,
  Wallet,
  ChartLine,
  Banknote,
  type LucideIcon,
} from 'lucide-react'
import type { CategoryType } from './types/category.types'
export const categoryTypeLabels: Record<CategoryType, string> = {
  INCOME: 'Ingreso',
  EXPENSE: 'Gasto',
  TRANSFER: 'Transferencia',
  INVESTMENT: 'Inversión',
}
export const categoryIcons: Record<string, LucideIcon> = {
  food: Utensils,
  transport: Car,
  home: House,
  shopping: ShoppingBag,
  work: Briefcase,
  income: CircleDollarSign,
  transfer: ArrowLeftRight,
  investment: ChartNoAxesCombined,
  education: BookOpen,
  transit: Bus,
  health: HeartPulse,
  pets: PawPrint,
  travel: Plane,
  services: ReceiptText,
  entertainment: Film,
  gift: Gift,
  savings: PiggyBank,
  taxes: Landmark,
  fitness: Dumbbell,
  technology: Smartphone,
  coffee: Coffee,
  briefcase: Briefcase,
  receipt: Receipt,
  store: Store,
  percent: Percent,
  'trending-up': TrendingUp,
  'rotate-ccw': RotateCcw,
  'circle-plus': CirclePlus,
  utensils: Utensils,
  bus: Bus,
  house: House,
  lightbulb: Lightbulb,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  film: Film,
  'shopping-bag': ShoppingBag,
  landmark: Landmark,
  shield: Shield,
  building: Building,
  'paw-print': PawPrint,
  plane: Plane,
  sparkles: Sparkles,
  'circle-minus': CircleMinus,
  'arrow-left-right': ArrowLeftRight,
  wallet: Wallet,
  'chart-line': ChartLine,
  banknote: Banknote,
}
export const categoryIconOptions = Object.keys(categoryIcons)
export const categoryIconLabels: Record<string, string> = {
  food: 'Comida',
  transport: 'Vehículo',
  home: 'Vivienda',
  shopping: 'Compras',
  work: 'Trabajo',
  income: 'Salario',
  transfer: 'Transferencia',
  investment: 'Inversión',
  education: 'Educación',
  transit: 'Transporte',
  health: 'Salud',
  pets: 'Mascotas',
  travel: 'Viajes',
  services: 'Servicios',
  entertainment: 'Entretenimiento',
  gift: 'Regalos',
  savings: 'Ahorro',
  taxes: 'Impuestos',
  fitness: 'Deporte',
  technology: 'Tecnología',
  coffee: 'Café',
  briefcase: 'Trabajo',
  receipt: 'Recibo',
  store: 'Ventas',
  percent: 'Comisión',
  'trending-up': 'Rendimiento',
  'rotate-ccw': 'Reembolso',
  'circle-plus': 'Otro ingreso',
  utensils: 'Alimentación',
  bus: 'Transporte público',
  house: 'Vivienda',
  lightbulb: 'Servicios',
  'heart-pulse': 'Salud',
  'graduation-cap': 'Educación',
  film: 'Entretenimiento',
  'shopping-bag': 'Compras',
  landmark: 'Deudas',
  shield: 'Seguros',
  building: 'Impuestos',
  'paw-print': 'Mascotas',
  plane: 'Viajes',
  sparkles: 'Cuidado personal',
  'circle-minus': 'Otro gasto',
  'arrow-left-right': 'Transferencia',
  wallet: 'Billetera',
  'chart-line': 'Crecimiento',
  banknote: 'Efectivo',
}
export const categoryColors = [
  '#2F855A',
  '#38A169',
  '#319795',
  '#3182CE',
  '#4299E1',
  '#6B46C1',
  '#805AD5',
  '#B83280',
  '#E53E3E',
  '#DD6B20',
  '#D69E2E',
  '#718096',
] as const
export const categoryColorLabels = [
  'Verde bosque',
  'Verde',
  'Menta',
  'Azul',
  'Celeste',
  'Violeta',
  'Lavanda',
  'Rosado',
  'Coral',
  'Naranja',
  'Amarillo',
  'Gris',
] as const
export const getCategoryIcon = (icon: string | null) =>
  icon && categoryIcons[icon] ? categoryIcons[icon] : Shapes
export const safeCategoryColor = (color: string | null) =>
  color && /^#[0-9A-Fa-f]{6}$/.test(color) ? color.toUpperCase() : '#64748B'
export const categoryContrastColor = (color: string | null) => {
  const safe = safeCategoryColor(color)
  const channels = [1, 3, 5].map(
    (index) => Number.parseInt(safe.slice(index, index + 2), 16) / 255,
  )
  const [red, green, blue] = channels.map((value) =>
    value <= 0.03928 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4,
  )
  return 0.2126 * red + 0.7152 * green + 0.0722 * blue > 0.21
    ? '#10211D'
    : '#FFFFFF'
}
