import {
  Bike,
  BriefcaseBusiness,
  Car,
  GraduationCap,
  HeartPulse,
  House,
  Laptop,
  Landmark,
  Plane,
  PiggyBank,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Target,
  TentTree,
  WalletCards,
  type LucideIcon,
} from 'lucide-react'

export const goalIcons: Record<string, LucideIcon> = {
  target: Target,
  savings: PiggyBank,
  bike: Bike,
  car: Car,
  laptop: Laptop,
  plane: Plane,
  house: House,
  shield: ShieldCheck,
  education: GraduationCap,
  health: HeartPulse,
  business: BriefcaseBusiness,
  investment: Landmark,
  shopping: ShoppingBag,
  cards: WalletCards,
  adventure: TentTree,
  sparkles: Sparkles,
}

export const goalIconOptions = Object.keys(goalIcons)

export const goalIconLabels: Record<string, string> = {
  target: 'Objetivo',
  savings: 'Ahorro',
  bike: 'Moto o bicicleta',
  car: 'Vehículo',
  laptop: 'Tecnología',
  plane: 'Viaje',
  house: 'Vivienda',
  shield: 'Fondo de emergencia',
  education: 'Educación',
  health: 'Salud',
  business: 'Negocio',
  investment: 'Inversión',
  shopping: 'Compra especial',
  cards: 'Pago importante',
  adventure: 'Experiencia',
  sparkles: 'Otro sueño',
}

export const goalColors = [
  '#2F855A',
  '#38A169',
  '#319795',
  '#3182CE',
  '#4299E1',
  '#6B46C1',
  '#805AD5',
  '#B83280',
  '#E53E3E',
  '#DD6B20',
  '#D69E2E',
  '#718096',
] as const

export const goalColorLabels = [
  'Verde bosque',
  'Verde',
  'Menta',
  'Azul',
  'Celeste',
  'Violeta',
  'Lavanda',
  'Rosado',
  'Coral',
  'Naranja',
  'Amarillo',
  'Gris',
] as const
